// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sitfhtntzrkpireosamj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdGZodG50enJrcGlyZW9zYW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzc1NzYsImV4cCI6MjA3MDkxMzU3Nn0.4u_fkNr9yeQzbT3VgHoHFWnyz58Cf8FjkN1ca4stlA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});